config/routes.rb
Talewiki::Application.routes.draw do
  resources :comments

  resources :users

  resources :roles

  resources :genres

  resources :tales

  get 'tags/:tag', to: 'tales#index', as: :tag

   root :to => 'tales#index'

   match ':controller(/:action(/:id))(.:format)'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
 belongs_to :tale
 belongs_to :user 
attr_accessible :comment_body, :submission_date
validates_presence_of :comment_body
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  layout "master"
  # GET /comments
  # GET /comments.json
  def index
@comments = Comment.order("comment_body").page(params[:page]).per(2)    

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new
    session[:tale_id] = params[:id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])
    @comment.tale_id = session[:tale_id]
    @comment.user_id = session[:user_id]

    
      if @comment.save
       flash[:notice] = 'Comment was successfully created.' 
       redirect_to :controller => 'tales', :action => 'index' 
      else
        render :action => "new" 
      end
    end
 

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Body %>
    <%= f.text_field :comment_body %>
  </div>

  <div class="field">
    <%= f.label :submission_date %><br />
    <%= f.date_select :submission_date %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<%= paginate @comments %>
<table>
  <tr>
    <th>Comment body</th>
    <th>Submission date</th>
    <th>Tale</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.comment_body %></td>
    <td><%= comment.submission_date %></td>
    <td><%= comment.tale_id %></td>
    <td><%= comment.user_id %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= link_to 'New Comment', new_comment_path %>
<%= link_to 'Back', tales_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', tales_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Comment body:</b>
  <%= @comment.comment_body %>
</p>

<p>
  <b>Submission date:</b>
  <%= @comment.submission_date %>
</p>

<p>
  <b>Tale:</b>
  <%= @comment.tale_id %>
</p>

<p>
  <b>User:</b>
  <%= @comment.user_id %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>