config/routes.rb
Talewiki::Application.routes.draw do
  resources :comments

  resources :users

  resources :roles

  resources :genres

  resources :tales

  get 'tags/:tag', to: 'tales#index', as: :tag

   root :to => 'tales#index'

   match ':controller(/:action(/:id))(.:format)'
end

app/models/tale.rb
class Tale < ActiveRecord::Base
acts_as_taggable 
belongs_to :genre  
belongs_to :user
has_many :comment

attr_accessible :body_text, :genres, :source, :status, :submission_date, :title, :tag_list
validates_presence_of :title, :body_text, :source

end

app/controllers/tales_controller.rb
class TalesController < ApplicationController
before_filter :check_authentic_user  
layout "master"
# GET /tales
  # GET /tales.json
  def index
   if params[:tags] 
   @tales = Tale.tagged_with(params[:tags]) 
else
 
   @tales = Tale.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tales }
    end
  end
end

  # GET /tales/1
  # GET /tales/1.json
  def show
    @tale = Tale.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tale }
    end
  end

  # GET /tales/new
  # GET /tales/new.json
  def new
     @genres=Genre.find(:all)    
     @tale = Tale.new
     @tale.status= "new"

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tale }
    end
  end

  # GET /tales/1/edit
  def edit
    @tale = Tale.find(params[:id])
    @tale.status="updated"
  end

  # POST /tales
  # POST /tales.json
  def create
    @tale = Tale.new(params[:tale])
    @tale.genre_id = params[:genre]
    @tale.user_id = session[:user_id]
    @tale.status = "new"
    

    respond_to do |format|
      if @tale.save
        format.html { redirect_to @tale, notice: 'Tale was successfully created.' }
        format.json { render json: @tale, status: :created, location: @tale }
      else
        format.html { render action: "new" }
        format.json { render json: @tale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tales/1
  # PUT /tales/1.json
  def update
    @tale = Tale.find(params[:id])
    @tale.status="updated"

    respond_to do |format|
      if @tale.update_attributes(params[:tale])
        format.html { redirect_to @tale, notice: 'Tale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tales/1
  # DELETE /tales/1.json
  def destroy
    @tale = Tale.find(params[:id])
    @tale.destroy

    respond_to do |format|
      format.html { redirect_to tales_url }
      format.json { head :no_content }
    end
  end
def tag_cloud
@tags = Tale.tag_counts_on(:tags)
end
end

app/helpers/tales_helper.rb
module TalesHelper
include ActsAsTaggableOn::TagsHelper
end

app/views/tales/_form.html.erb
<%= form_for(@tale) do |f| %>
  <% if @tale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tale.errors.count, "error") %> prohibited this tale from being saved:</h2>

      <ul>
      <% @tale.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body_text %><br />
    <%= f.text_area :body_text %>
  </div>
  <div class="field">
    <%= f.label :submission_date %><br />
    <%= f.date_select :submission_date %>
  </div>
  <div class="field">
    <%= f.label :source %><br />
    <%= f.text_field :source %>
  </div>
<div class="field">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list %>
  </div>
  
<p><label for="genre_name">Genre<br/>
<select name="genre">
</p>
<% @genres.each do |genre| %>
<option value="<%= genre.id %>">
<%= genre.genre_name %>
</option>
<% end %>
</select>
 
<% end %>

app/views/tales/_form_edit.html.erb
<%= form_for(@tale) do |f| %>
  <% if @tale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tale.errors.count, "error") %> prohibited this tale from being saved:</h2>

      <ul>
      <% @tale.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body_text %><br />
    <%= f.text_area :body_text %>
  </div>
  <div class="field">
    <%= f.label :submission_date %><br />
    <%= f.date_select :submission_date %>
  </div>
  <div class="field">
    <%= f.label :source %><br />
    <%= f.text_field :source %>
  </div>
<div class="field">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list %>
  </div


<p><label for="tale_status">Status</label><br/>
<%= @tale.status  %></p>

<p><label for="genre_name">Genre</label><br/>
<%=@tale.genre.genre_name %></p>


<div class="actions">
<%= f.submit %>
</div>
<% end %>

app/views/tales/edit.html.erb
<h1>Editing tale</h1>


<%= render :partial => 'form_edit' -%>
<%= link_to 'Show', :action => 'show', :id => @tale %> |
<%= link_to 'Back', tales_path %>

app/views/tales/index.html.erb
<!DOCTYPE html>
<html>

<body>
<h1>Listing tales</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body text</th>
    <th>Submission date</th>
    <th>Source</th>
    <th>Status</th>
    
  </tr>

<% @tales.each do |tale| %>
  <tr>
    <td><%= tale.title %></td>
    <td><%= tale.body_text %></td>
    <td><%= tale.submission_date %></td>
    <td><%= tale.source %></td>
    <td><%= tale.status %></td>
    <td> Tags:<%= raw tale.tags.map { |t| link_to t, tag_path(t) }.join(',') %>
    <td><%= link_to 'Show', tale %></td>
   
    <td><%= link_to 'Edit', edit_tale_path(tale) %></td>
    <td><%= link_to 'Destroy', tale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

</table>
<br />




<%= link_to 'New Tale', new_tale_path %>
</body>
</html>

app/views/tales/new.html.erb
<h1>New tale</h1>

<%= render :partial => 'form' %>
<%= submit_tag "Create" %>

<%= link_to 'Back', tales_path %>

app/views/tales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @tale.title %>
</p>

<p>
  <b>Body text:</b>
  <%= @tale.body_text %>
</p>

<p>
  <b>Submission date:</b>
  <%= @tale.submission_date %>
</p>

<p>
  <b>Source:</b>
  <%= @tale.source %>
</p>

<p>
  <b>Status:</b>
  <%= @tale.status %>
</p>
<p>
  <b>Tag:</b>
  <%= @tale.tag_list %>
</p>

<%= link_to 'Edit', edit_tale_path(@tale) %> |
<%= link_to 'Back', tales_path %>
<%= link_to 'Add Comment', :controller=>'comments', :action => 'new', :id => @tale.id %>
<%= link_to 'View Comments', :controller=>'comments', :action => 'index', :id => @tale.id %>
<%= link_to 'Add tags', :controller=>'tags', :action => 'new', :id => @tale.id %>